### ISSUE TITLE
How to customize colors?

### ISSUE THREAD

**Issue by davidvavra** [lemillion12/multi-floating-action-button#1]
Hi, the decriptions states:

> Highly customizable (label, icon and background colors, themes support)

But I can't find how to customize default look, for example background colors of FABs?

**Comment by msanyam** [comment]
Hello @davidvavra
Since the library leverages MaterialTheme.colorScheme.primaryContainer color from [Material Design 3](https://m3.material.io/libraries/mdc-android/getting-started) for the color of the FABs, you can update MaterialTheme.colorScheme.primaryContainer for any customizations. Let me know if you have further queries.

**Comment by davidvavra** [comment]
But how to change it only for FAB but not for the whole theme? Some example would be nice, preferably in the README.md

**Comment by msanyam** [comment]
Unfortunately customization of the FAB outside of the Theme is not currently supported.

**Comment by davidvavra** [comment]
OK I ended up copy-pasting the code and modifying it directly. But thanks for it, it helped a lot.

**Comment by msanyam** [comment]
Do you want to raise a PR and make it available to others?

**Comment by davidvavra** [comment]
It would be a lot of effort to make it generic, I hardcoded the style just for our use-case. Maybe if there is a demand for it here.
